name: Render still
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Which text should it say?"
        required: true
        default: "Welcome to Remotion"
      description:
        description: "Which subtitle should it be?"
        required: true
        default: "black"
jobs:
  render:
    name: Render still
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run render -- --props="$WORKFLOW_INPUT"
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - uses: actions/upload-artifact@v2
        with:
          name: still.png
          path: out/still.png
